services:
  broker:
    image: rabbitmq:3.10.7-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: mongo:5.0.12
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest

  db-ui:
    image: mongo-express:0.54.0
    restart: always
    depends_on:
      - "db"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: guest
      ME_CONFIG_MONGODB_ADMINPASSWORD: guest
      ME_CONFIG_MONGODB_SERVER: db