services:
  clientapi:
    build: ./clientApi
    restart: always
    depends_on:
      - "broker"
      - "userservice"
    ports:
      - 8080:8080
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      MB_HOST: broker
      MB_PORT: 5672
      MB_USERNAME: guest
      MB_PASSWORD: guest
      ROOM_SERVICE_HOST: roomservice
      ROOM_SERVICE_PORT: 50051
      USER_SERVICE_HOST: userservice
      USER_SERVICE_PORT: 50052
  
  createroomsubscriber:
    build: ./createroomsubscriber
    restart: always
    depends_on:
      - "broker"
      - "db"
    environment:
      MB_HOST: broker
      MB_PORT: 5672
      MB_USERNAME: guest
      MB_PASSWORD: guest
      DB_HOST: db
      DB_PORT: 27017
      DB_USERNAME: guest
      DB_PASSWORD: guest

  createusersubscriber:
    build: ./createusersubscriber
    restart: always
    depends_on:
      - "broker"
      - "db"
    environment:
      MB_HOST: broker
      MB_PORT: 5672
      MB_USERNAME: guest
      MB_PASSWORD: guest
      DB_HOST: db
      DB_PORT: 27017
      DB_USERNAME: guest
      DB_PASSWORD: guest

  roomservice:
    build: ./roomservice
    restart: always
    depends_on:
      - "db"
    environment:
      HOST: 0.0.0.0
      PORT: 50051
      DB_HOST: db
      DB_PORT: 27017
      DB_USERNAME: guest
      DB_PASSWORD: guest

  userservice:
    build: ./userservice
    restart: always
    depends_on:
      - "db"
    environment:
      HOST: 0.0.0.0
      PORT: 50052
      DB_HOST: db
      DB_PORT: 27017
      DB_USERNAME: guest
      DB_PASSWORD: guest

  broker:
    image: rabbitmq:3.10.7-management-alpine
    restart: always
    ports:
      - 15672:15672

  db:
    image: mongo:5.0.12
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
    ports:
      - 27017:27017

  db-ui:
    image: mongo-express:0.54.0
    restart: always
    depends_on:
      - "db"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: guest
      ME_CONFIG_MONGODB_ADMINPASSWORD: guest
      ME_CONFIG_MONGODB_SERVER: db